sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ ./build.sh
        - docker images kamikat/mxnet-onbuild
        - docker push kamikat/mxnet-onbuild
