sudo: true
dist: trusty

jobs:
  include:
    - stage: build cu70 images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ CI_BUILD=1 TARGET=cu70 ./build.sh
    - stage: build cu75 images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ CI_BUILD=1 TARGET=cu75 ./build.sh
    - stage: build cu80 images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ CI_BUILD=1 TARGET=cu80 ./build.sh
    - stage: build cu9x images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ CI_BUILD=1 TARGET=cu9x ./build.sh
