sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker images
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - IMAGE_PREFIX=kamikat/ CI_BUILD=1 ./build.sh
